### ISSUE TITLE
"To run this application, you must install .NET Core. Would you like to download it now?" Error Issue

### ISSUE THREAD

**Issue by ERA4O4** [kemo14331/Particle-Converter#25]
A decent 2 months - ish ago i tried to download this. Then, I got the "To run this application, you must install .NET Core. Would you like to download it now?" message. I clicked Yes. Nothing Happened. I clicked around downloading the correct .NET Core versions needed of the website. Nothing happened. Please help.
![screnshot](https://github.com/kemo14331/Particle-Converter/assets/134170555/05f1fb18-5e2e-4f15-8c67-b5bd49212dbd)

**Comment by dfggrfe** [comment]
If you download .NET Core 3.1, its works ! To download .NET Core 3.1, you can use the following link:

https://dotnet.microsoft.com/en-us/download/dotnet/3.1

![image](https://github.com/kemo14331/Particle-Converter/assets/76404065/8d6b1d59-9572-418d-baaa-075ed10e8259)

**Comment by ERA4O4** [comment]
Good news: IT WORKS!!!!!

Thank you SO much for the help. I've been trying to get this to work for
months now but its finally working. Your actually a legend, thank you soooo
much :)))

**Comment by Nyxiality** [comment]
Have tried this multiple times now, still not working

**Comment by JadeJuno** [comment]
Does it have to be the 3.1 version? Or can I get a newer version instead?

**Comment by ERA4O4** [comment]
Guys, make sure you run the .NET core setup wizard once you download it. I think thats where I went wrong.
