### ISSUE TITLE
Enforce English floating point format on export

### ISSUE THREAD

**Issue by Androkai** [kemo14331/Particle-Converter#3]
Hi, that's a really nice little tool you made. 👍

I played a bit with it on a system with German locale and noticed a small problem: The German presentation for floating point values switches dots and commas so one thousand `1,000.00` will become `1.000,00`. The problem is that the tool will use the values in the same presentation on export resulting and Minecraft complaining about an invalid format in the function. Therefore it would be nice to have the converter enforcing the English presentation on export.

Keep up the great work!

**Comment by kemo14331** [comment]
Thanks for the bug report! 😆 
The problem has been fixed in version 1.0.3

**Comment by Androkai** [comment]
Works, thx a lot 👍
