### ISSUE TITLE
Must install .Net Core but I've alredy installed it.

### ISSUE THREAD

**Issue by dagidagi** [kemo14331/Particle-Converter#30]
- I downloaded .NET SDK 3.1.32 and this showed up because it didn't install when I clicked yes.

- To fix it I uninstalled ASP.NET Core Runtime 3.1.32 and downloaded ASP.NET Core Runtime 3.1.0 and again, this showed up.

- Then I tried using the 1.0.3 version of the ParticleConverter but that also didn't work.

What else can I do?

![resim_2024-02-28_212250168](https://github.com/kemo14331/Particle-Converter/assets/47927015/f670fb7a-b059-4e6e-96f8-8f89bdab9f6a)

**Comment by dagidagi** [comment]
Fixed it

**Comment by MistakingManx** [comment]
Hey, even if it's like entirely user error still tell how you fixed it qwq
